import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'km' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  km: {
    app_title: 'កម្មវិធីគ្រប់គ្រងទិន្នន័យ វត្តស្នាយដួច',
    nav_home: 'ទំព័រដើម',
    nav_finance: 'ចំណូល-ចំណាយ',
    nav_list: 'បញ្ជីផ្សេងៗ',
    nav_reports: 'របាយការណ៍',
    nav_account: 'គណនី',
    
    common_back: 'ត្រឡប់ក្រោយ',
    common_loading: 'កំពុងផ្ទុក...',
    common_saving: 'កំពុងរក្សាទុក...',
    common_no_data: 'មិនទាន់មានទិន្នន័យនៅឡើយទេ',
    common_show: 'បង្ហាញ',
    common_hide: 'លាក់',
    common_search: 'ស្វែងរក...',

    profile_account_menu: 'គណនី',
    profile_security_menu: 'ពាក្យសម្ងាត់ និងសុវត្ថិភាព',
    profile_setting_menu: 'ការកំណត់',
    profile_syslog_menu: 'កំណត់ត្រាប្រព័ន្ធ',
    profile_setting_modal_title: 'ការកំណត់',
    profile_setting_lang_heading: 'ភាសា:',
    profile_setting_lang_km: 'ភាសាខ្មែរ',
    profile_setting_lang_km_desc: 'អត្ថបទទាំងអស់ក្នុងកម្មវិធីនេះនឹងត្រូវប្ដូរទៅជាភាសាខ្មែរ។',
    profile_setting_lang_en: 'ភាសាអង់គ្លេស',
    profile_setting_lang_en_desc: 'អត្ថបទទាំងអស់ក្នុងកម្មវិធីនេះនឹងត្រូវប្ដូរទៅជាភាសាអង់គ្លេស។',
    profile_setting_theme_heading: 'ស្បែក:',
    profile_setting_theme_dark: 'រចនាប័ទ្មងងឹត',
    profile_setting_theme_light: 'រចនាប័ទ្មភ្លឺ',
    profile_setting_fontsize_heading: 'ទំហំអក្សរ:',
    profile_setting_fontsize_sm: 'តូច',
    profile_setting_fontsize_sm_desc: '៩០% - ស័ក្តិសមសម្រាប់អេក្រង់តូច ឬចង់ឃើញទិន្នន័យច្រើន',
    profile_setting_fontsize_md: 'ធម្មតា',
    profile_setting_fontsize_md_desc: '១០០% - ទំហំស្ដង់ដាររបស់កម្មវិធី',
    profile_setting_fontsize_lg: 'ធំ',
    profile_setting_fontsize_lg_desc: '១១០% - ស្រួលមើល និងអានបានច្បាស់ល្អ',
    profile_setting_fontsize_xl: 'ធំបំផុត',
    profile_setting_fontsize_xl_desc: '១២០% - អក្សរធំខ្លាំង ស័ក្តិសមសម្រាប់មនុស្សចាស់',
    profile_setting_fontsize_preview: 'គំរូអក្សរ៖ វត្តស្នាយដួច ចំណូល-ចំណាយ និងបញ្ជីឈ្មោះ ១,០០០ ដុល្លារ',
    profile_setting_role_heading: 'តួនាទី:',
    profile_setting_role_admin: 'អ្នកគ្រប់គ្រង',
    profile_setting_role_user: 'អ្នកប្រើប្រាស់ទូទៅ',
    profile_setting_btn_use: 'ជ្រើសរើស',
    profile_setting_btn_used: 'កំពុងប្រើ',
    profile_setting_storage_heading: 'អង្គចងចាំ:',
    profile_setting_storage_label: 'ទិន្នន័យបណ្ដោះអាសន្ន',
    profile_setting_storage_desc: 'លុបកំណត់ត្រាប្រព័ន្ធ និងទិន្នន័យបណ្ដោះអាសន្នដើម្បីឱ្យកម្មវិធីដំណើរការស្រាលជាងមុន។',
    profile_setting_storage_clean_btn: 'សម្អាត',
    profile_setting_storage_confirm: 'បញ្ជាក់ការសម្អាត?',
    profile_setting_storage_cleaned: 'បានសម្អាត',
    profile_role_menu: 'ផ្លាស់ប្ដូរសិទ្ធិអ្នកប្រើប្រាស់',
    profile_role_modal_title: 'ផ្លាស់ប្ដូរសិទ្ធិអ្នកប្រើប្រាស់',
    profile_role_admin_title: 'អ្នកគ្រប់គ្រង',
    profile_role_admin_desc: 'មានសិទ្ធិពេញលេញក្នុងការគ្រប់គ្រង កែប្រែ បញ្ចូល និងលុបទិន្នន័យទាំងអស់',
    profile_role_user_title: 'អ្នកប្រើប្រាស់ទូទៅ',
    profile_role_user_desc: 'សម្រាប់តែការមើល និងកត់ត្រាទិន្នន័យកម្រិតស្ដង់ដារ',
    profile_role_current: 'កំពុងប្រើប្រាស់',
    profile_security_modal_title: 'ពាក្យសម្ងាត់ និងសុវត្ថិភាព',
    profile_change_password_title: 'ពាក្យសម្ងាត់',
    profile_change_password_desc: 'ផ្លាស់ប្ដូរពាក្យសម្ងាត់គណនី',
    profile_pin_balance_title: 'PIN មើលទឹកប្រាក់',
    profile_pin_balance_set: 'បានកំណត់រួចរាល់',
    profile_pin_balance_unset: 'មិនទាន់បានកំណត់',
    profile_settings_heading: 'ការកំណត់:',
    profile_change_lang: 'ផ្លាស់ប្ដូរភាសា',
    profile_change_theme: 'ផ្លាស់ប្ដូរស្បែក',
    profile_theme_modal_title: 'ផ្លាស់ប្ដូរស្បែក',
    profile_theme_light_label: 'ភ្លឺ',
    profile_theme_dark_label: 'ងងឹត',
    profile_mgmt_heading: 'ការគ្រប់គ្រង:',
    profile_certificates: 'លិខិតផ្សេងៗ',
    profile_users: 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
    profile_introduced: 'របៀបដំឡើងកម្មវិធី',
    profile_about: 'អំពីកម្មវិធី',
    profile_logout: 'ចាកចេញពីគណនី',

    theme_dark: 'ងងឹត',
    theme_light: 'ភ្លឺ',
    
    about_tab_info: 'អំពីកម្មវិធី',
    about_tab_introduced: 'របៀបដំឡើង',
    about_purpose: 'គោលបំណង',
    about_purpose_desc: 'កម្មវិធីនេះបង្កើតឡើងដើម្បីគ្រប់គ្រងប្រព័ន្ធទិន្នន័យចំណូល ចំណាយ និងបញ្ជីឈ្មោះសប្បុរសជនផ្សេងៗរបស់វត្តស្នាយដួច។',
    about_dev: 'រៀបចំ និងអភិវឌ្ឍដោយ',
    about_tech: 'បច្ចេកវិទ្យា',
    about_close: 'បិទ',
    about_version: 'កំណែ',
    install_already_installed: 'កម្មវិធីបានដំឡើងរួចរាល់នៅលើឧបករណ៍នេះ',
    install_android_desc: 'លោកអ្នកអាចដំឡើងកម្មវិធីវត្តស្នាយដួចលើទូរស័ព្ទ Android ដើម្បីបើកប្រើប្រាស់បានលឿន ងាយស្រួល និងរហ័សទាន់ចិត្ត។',
    install_btn_installing: 'កំពុងរៀបចំ...',
    install_btn_install: 'ដំឡើងកម្មវិធី',
    install_android_steps_title: 'ជំហានដំឡើងតាម Chrome ឬ Samsung Internet:',
    install_android_step_1_prefix: 'បើកកម្មវិធីតាមរយៈ ',
    install_android_step_1_or: ' ឬ ',
    install_android_step_2: 'ចុចលើសញ្ញាម៉ឺនុយជម្រើស (⋮) នៅជ្រុងខាងលើស្តាំ',
    install_android_step_3: 'ជ្រើសរើសយក «ដំឡើងកម្មវិធី» ឬ «បន្ថែមទៅអេក្រង់ដើម»',
    install_android_step_4: 'ចុច «ដំឡើង» ដើម្បីបញ្ចប់ការដំឡើង',
    install_ios_desc: 'សម្រាប់ទូរស័ព្ទ iPhone / iPad សូមបើកដំណើរការតាមរយៈកម្មវិធី Safari រួចអនុវត្តតាមជំហានខាងក្រោម៖',
    install_ios_steps_title: 'ជំហានបន្ថែមទៅលើអេក្រង់ដើម:',
    install_ios_step_1: 'បើកតំណភ្ជាប់ក្នុងកម្មវិធី Safari',
    install_ios_step_2: 'ចុចលើប៊ូតុង ចែករំលែក នៅរបារខាងក្រោម',
    install_ios_step_3: 'អូសចុះក្រោម រួចជ្រើសរើស «Add to Home Screen»',
    install_ios_step_4: 'ចុច «បន្ថែម» នៅជ្រុងខាងលើស្តាំជាការស្រេច',
    install_ios_copy_btn: 'ចម្លងតំណភ្ជាប់ដើម្បីបើកក្នុង Safari',
    install_ios_copied: 'បានចម្លងតំណភ្ជាប់រួចរាល់!',
    
    lang_khmer: 'ភាសាខ្មែរ',
    lang_english: 'English',

    dashboard_title: 'វិភាគទិន្នន័យ',
    dashboard_total_report: 'របាយការណ៍សរុប (រយៈពេល {count} សីល)',
    dashboard_total_income: 'ចំណូលសរុប',
    dashboard_total_expense: 'ចំណាយសរុប',
    dashboard_actual_balance: 'សាច់ប្រាក់នៅសល់ជាក់ស្តែង',
    dashboard_chart_title: 'ចំណូល និងចំណាយតាមវេនសីល',
    dashboard_income: 'ចំណូល',
    dashboard_expense: 'ចំណាយ',
    dashboard_pie_title: 'សមាមាត្រហិរញ្ញវត្ថុ',
    dashboard_amount: 'ចំនួន',
    dashboard_high_donors: 'សប្បុរសជនថវិកាកម្រិតខ្ពស់',
    dashboard_donors_count: '{count} នាក់',

    records_title: 'ចំណូល-ចំណាយ',
    records_total_periods: 'សរុប {count} កាលបរិច្ឆេទ',
    records_btn_add_new: 'បន្ថែមថ្មី',
    records_add_new: 'បន្ថែមចំណូល-ចំណាយ',
    records_prev_balance: 'បច្ច័យនៅសល់ពីមុន',
    records_current_balance: 'នៅសល់ជាក់ស្តែង',
    records_total_income: 'ចំណូលសរុប',
    records_total_expense: 'ចំណាយសរុប',
    records_empty_income: 'មិនទាន់មានទិន្នន័យចំណូលនៅឡើយទេ',
    records_empty_expense: 'មិនទាន់មានទិន្នន័យចំណាយនៅឡើយទេ',
    records_add_new_title: 'បញ្ជូលទិន្នន័យថ្មី',
    records_type_income: 'ចំណូល',
    records_type_expense: 'ចំណាយ',
    records_description_income: 'ឈ្មោះសប្បុរសជន',
    records_description_income_ph: 'សូមបញ្ជូលឈ្មោះ',
    records_description_expense: 'បរិយាយ (មុខទំនិញ)',
    records_description_expense_ph: 'ឧ. ទិញទឹកសុទ្ធ...',
    records_amount: 'ចំនួនទឹកប្រាក់ (រៀល)',
    records_amount_ph: '00,000',
    records_date: 'កាលបរិច្ឆេទ',
    records_note: 'ចំណាំផ្សេងៗ',
    records_note_ph: 'មិនចាំបាច់ក៏បាន',
    records_save: 'រក្សាទុកទិន្នន័យ',

    lists_main_title: 'បញ្ជីផ្សេងៗ',
    lists_category_roof: 'បញ្ជីឈ្មោះកសាងដំបូលព្រះវិហារ',
    lists_category_kathina: 'បុណ្យកឋិន',
    lists_category_general: 'បញ្ជីទូទៅ',
    lists_status_active: 'កំពុងប្រតិបត្តិការ',
    lists_status_completed: 'បានបញ្ចប់',
    lists_no_lists: 'មិនទាន់មានបញ្ជីនៅឡើយទេ',
    list_title: 'បញ្ជីឈ្មោះ',
    list_add_new: 'បន្ថែមទិន្នន័យ',
    list_search: 'ស្វែងរកឈ្មោះ ឬទីកន្លែង...',
    list_date: 'កាលបរិច្ឆេទ',
    list_total_records: 'សរុបទិន្នន័យ',
    list_total_amount: 'សរុប',
    list_empty: 'មិនមានទិន្នន័យនៅឡើយទេ',
    list_referrer: 'តាមរយៈ',
    list_edit_title: 'កែប្រែទិន្នន័យ',
    list_add_title: 'បន្ថែមទិន្នន័យថ្មី',
    list_name: 'ឈ្មោះ',
    list_name_ph: 'បញ្ចូលឈ្មោះ...',
    list_amount: 'ចំនួនទឹកប្រាក់ (រៀល)',
    list_amount_ph: 'ឧ. 100000',
    list_note: 'ផ្នែក',
    list_note_ph: 'ឧ. ភ្នំពេញ...',
    list_ref: 'អ្នកណែនាំ / តាមរយៈ (មិនចាំបាច់)',
    list_ref_ph: 'បញ្ចូលឈ្មោះអ្នកណែនាំ...',
    list_cancel: 'បោះបង់',
    list_save: 'រក្សាទុក',
    list_alert_delete: 'តើអ្នកពិតជាចង់លុបទិន្នន័យនេះមែនទេ?',
    list_alert_error: 'មានបញ្ហាក្នុងការរក្សាទុកទិន្នន័យ',
    list_alert_del_error: 'មានបញ្ហាក្នុងការលុបទិន្នន័យ',

    reports_saved_title: 'របាយការណ៍ដែលបានរក្សាទុក',
    reports_empty: 'មិនទាន់មានរបាយការណ៍ដែលបានរក្សាទុកទេ',
    reports_preview_title: 'មើលរូបរបាយការណ៍',
    reports_download: 'ទាញយក',
    reports_delete: 'លុប',
    reports_delete_confirm_title: 'បញ្ជាក់ការលុប',
    reports_delete_confirm_msg: 'តើអ្នកពិតជាចង់លុបរបាយការណ៍នេះមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
    reports_cancel: 'បោះបង់',
    reports_preview_hint: 'ចុចដើម្បីមើលរូបភាព',

    cert_title: 'លិខិតថ្លែងអំណរគុណ',
    cert_total: 'សរុប {count}',
    cert_search_ph: 'ស្វែងរកឈ្មោះ...',
    cert_not_found: 'រកមិនឃើញលិខិតដែលស្វែងរកទេ',
    cert_empty: 'មិនទាន់មានលិខិតថ្លែងអំណរគុណទេ',
    cert_btn_view: 'មើល',
    cert_btn_download: 'ទាញយក',
    cert_btn_delete: 'លុប',
    cert_modal_view_title: 'មើលរូបភាពលិខិត',
    cert_delete_confirm_title: 'លុបលិខិតថ្លែងអំណរគុណ?',
    cert_delete_confirm_desc: 'តើអ្នកពិតជាចង់លុបលិខិតនេះមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',

    users_title: 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
    users_subtitle: 'គ្រប់គ្រងសិទ្ធិ និងគណនី',
    users_tab_list: 'បញ្ជីអ្នកប្រើប្រាស់',
    users_tab_advanced: 'ការកំណត់កម្រិតខ្ពស់',
    users_col_id: 'ល.រ / ID',
    users_col_name: 'ឈ្មោះ / Name',
    users_col_email: 'អ៊ីមែល / Email',
    users_col_role: 'តួនាទី / Roles',
    users_col_status: 'ស្ថានភាព / Status',
    users_col_actions: 'សកម្មភាព / Actions',
    users_search_ph: 'ស្វែងរកឈ្មោះ អ៊ីមែល ឬលេខទូរស័ព្ទ...',
    users_no_name: 'គ្មានឈ្មោះ',
    users_registered_at: 'បានចុះឈ្មោះ:',
    users_role_admin: 'អ្នកគ្រប់គ្រង',
    users_role_user: 'អ្នកប្រើប្រាស់',
    users_btn_reset_pwd: 'ប្ដូរពាក្យសម្ងាត់',
    users_reset_pwd_title: 'ប្ដូរពាក្យសម្ងាត់ថ្មី',
    users_new_pwd_ph: 'បញ្ចូលពាក្យសម្ងាត់ថ្មី (យ៉ាងហោច ៦ ខ្ទង់)',
    users_btn_save_pwd: 'ផ្លាស់ប្ដូរពាក្យសម្ងាត់',
    users_confirm_role_change: 'តើអ្នកពិតជាចង់ប្តូរសិទ្ធិអ្នកប្រើប្រាស់នេះទៅជា {role} មែនទេ?',

    profile_title: 'ប្រវត្តិរូប',
    profile_view_edit: 'មើលប្រវត្តិរូប និងកែប្រែ',
    profile_settings: 'ការគ្រប់គ្រង',
    profile_finance_mgmt: 'ចំណូល-ចំណាយ',
    profile_list_mgmt: 'បញ្ជីផ្សេងៗ',
    profile_security_title: 'គណនីរបស់អ្នកមានសុវត្ថិភាព',
    profile_security_desc: 'ទិន្នន័យរបស់អ្នកត្រូវបានការពារយ៉ាងល្អ',
    profile_others: 'ការកំណត់',
    profile_edit_title: 'កែប្រែប្រវត្តិរូប',
    profile_edit_photo: 'ចុចលើកាមេរ៉ាដើម្បីប្តូររូបភាព',
    profile_full_name: 'ឈ្មោះពេញ',
    profile_password: 'ពាក្យសម្ងាត់',
    profile_password_ph: 'ទុកទទេបើមិនចង់ដូរពាក្យសម្ងាត់ថ្មី',
    profile_save_changes: 'រក្សាទុកការកែប្រែ',
    profile_saving: 'កំពុងរក្សាទុក...',
    profile_role_admin: 'អ្នកគ្រប់គ្រង',
    profile_role_user: 'អ្នកប្រើប្រាស់',
    profile_personal_details: 'ព័ត៌មានផ្ទាល់ខ្លួន',
    profile_khmer_name: 'ឈ្មោះខ្មែរ',
    profile_khmer_name_ph: 'បញ្ចូលឈ្មោះជាភាសាខ្មែរ',
    profile_latin_name: 'ឈ្មោះឡាតាំង',
    profile_latin_name_ph: 'បញ្ចូលឈ្មោះជាអក្សរឡាតាំង',
    profile_unverified: 'មិនទាន់ផ្ទៀងផ្ទាត់',
    profile_unverified_desc: 'សូមបំពេញព័ត៌មានបន្ថែម (ថ្ងៃខែឆ្នាំកំណើត ទីលំនៅ លេខទូរស័ព្ទ) ដើម្បីផ្ទៀងផ្ទាត់គណនី',
    profile_family_name: 'គោត្តនាម',
    profile_family_name_ph: 'គោត្តនាម',
    profile_given_name: 'នាម',
    profile_given_name_ph: 'នាម',
    profile_dob: 'ថ្ងៃខែឆ្នាំកំណើត',
    profile_dob_ph: 'ថ្ងៃ/ខែ/ឆ្នាំ',
    profile_gender: 'ភេទ',
    profile_gender_male: 'ប្រុស',
    profile_gender_female: 'ស្រី',
    profile_address: 'អាសយដ្ឋាន',
    profile_address_ph: 'ទីលំនៅ',
    profile_email: 'អ៊ីម៉ែល',
    profile_email_ph: 'អ៊ីម៉ែល',
    profile_phone: 'លេខទូរស័ព្ទ',
    profile_phone_ph: 'លេខទូរស័ព្ទ',
    profile_btn_edit: 'កែប្រែ',
    profile_btn_save: 'រក្សាទុកប្រវត្តិរូប',
    profile_save_success: 'រក្សាទុកទិន្នន័យជោគជ័យ!',
    profile_save_error: 'មានបញ្ហាក្នុងការរក្សាទុកទិន្នន័យ។',
    profile_avatar_success: 'បានប្តូររូប Profile ជោគជ័យ!',
    profile_avatar_error: 'មានបញ្ហាក្នុងការបញ្ចូលរូបភាព។',
    dashboard_verify_pin_title: 'បញ្ជាក់ PIN',
    dashboard_verify_pin_sub: 'សូមបញ្ចូល PIN ៤ ខ្ទង់របស់អ្នកដើម្បីមើលទឹកប្រាក់',

    install_title: 'ទាញយកកម្មវិធី',
    install_desc: 'ទាញយកកម្មវិធីនេះដាក់លើអេក្រង់ទូរស័ព្ទរបស់អ្នក ដើម្បីងាយស្រួលប្រើប្រាស់។',
    install_btn: 'ទាញយក',

    sec_title: 'ពាក្យសម្ងាត់ និងសុវត្ថិភាព',
    sec_pwd_label: 'ពាក្យសម្ងាត់',
    sec_pwd_desc: 'យើងណែនាំឱ្យប្រើពាក្យសម្ងាត់ដែលមានសុវត្ថិភាព និងមិនប្រើនៅកន្លែងផ្សេង។',
    sec_pin_label: 'PIN',
    sec_pin_desc: 'ផ្លាស់ប្ដូរ PIN ដែលប្រើប្រាស់នៅលើកម្មវិធីនេះ។',
    sec_email_label: 'អ៊ីម៉ែល',
    sec_phone_label: 'លេខទូរស័ព្ទ',
    sec_contact_label: 'ទំនាក់ទំនង:',
    sec_change_btn: 'change',
    sec_change_cap_btn: 'Change',
    
    sec_modal_pwd_title: 'ផ្លាស់ប្ដូរពាក្យសម្ងាត់',
    sec_modal_pwd_new: 'ពាក្យសម្ងាត់ថ្មី',
    sec_modal_pwd_new_ph: 'បញ្ចូលពាក្យសម្ងាត់ថ្មី (យ៉ាងហោចណាស់ ៦ តួ)',
    sec_modal_pwd_confirm: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    sec_modal_pwd_confirm_ph: 'បញ្ចូលពាក្យសម្ងាត់ថ្មីម្ដងទៀត',
    sec_modal_pwd_save: 'រក្សាទុកការផ្លាស់ប្ដូរ',
    sec_modal_pwd_err_len: 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
    sec_modal_pwd_err_match: 'ពាក្យសម្ងាត់ទាំងពីរមិនដូចគ្នាទេ',
    sec_modal_pwd_err_fail: 'មានបញ្ហាក្នុងការផ្លាស់ប្ដូរពាក្យសម្ងាត់',
    sec_modal_pwd_success: 'បានផ្លាស់ប្ដូរពាក្យសម្ងាត់ដោយជោគជ័យ',

    sec_modal_pin_verify_title: 'បញ្ជាក់ PIN ចាស់',
    sec_modal_pin_verify_sub: 'សូមបញ្ចូល PIN ចាស់របស់អ្នក',
    sec_modal_pin_new_title: 'កំណត់ PIN ថ្មី',
    sec_modal_pin_new_sub: 'សូមបញ្ចូល PIN ថ្មី ៤ ខ្ទង់',
    sec_modal_pin_confirm_title: 'បញ្ជាក់ PIN ថ្មី',
    sec_modal_pin_confirm_sub: 'សូមបញ្ចូល PIN ថ្មីម្ដងទៀត ដើម្បីបញ្ជាក់',
    sec_modal_pin_err_match: 'លេខកូដ PIN ទាំងពីរមិនដូចគ្នាទេ',
    sec_modal_pin_err_incorrect: 'លេខកូដ PIN ចាស់មិនត្រឹមត្រូវទេ',
    sec_modal_pin_err_fail: 'មានបញ្ហាក្នុងការកំណត់ PIN',
    sec_modal_pin_success: 'បានកំណត់លេខកូដ PIN ដោយជោគជ័យ',

    sec_modal_email_title: 'ផ្លាស់ប្ដូរអ៊ីម៉ែល',
    sec_modal_email_label: 'អ៊ីម៉ែលថ្មី',
    sec_modal_email_ph: 'name@example.com',
    sec_modal_email_save: 'រក្សាទុកការផ្លាស់ប្ដូរ',
    sec_modal_email_err_invalid: 'សូមបញ្ចូលអ៊ីម៉ែលឱ្យបានត្រឹមត្រូវ',
    sec_modal_email_err_fail: 'មានបញ្ហាក្នុងការផ្លាស់ប្ដូរអ៊ីម៉ែល',
    sec_modal_email_success: 'បានផ្លាស់ប្ដូរអ៊ីម៉ែលដោយជោគជ័យ',

    sec_modal_phone_title: 'ផ្លាស់ប្ដូរលេខទូរស័ព្ទ',
    sec_modal_phone_label: 'លេខទូរស័ព្ទថ្មី',
    sec_modal_phone_ph: '012 345 678',
    sec_modal_phone_save: 'រក្សាទុកការផ្លាស់ប្ដូរ',
    sec_modal_phone_err_req: 'សូមបញ្ចូលលេខទូរស័ព្ទ',
    sec_modal_phone_err_fail: 'មានបញ្ហាក្នុងការផ្លាស់ប្ដូរលេខទូរស័ព្ទ',
    sec_modal_phone_success: 'បានផ្លាស់ប្ដូរលេខទូរស័ព្ទដោយជោគជ័យ',

    sec_modal_admin_title: 'ទំនាក់ទំនង Admin',
    sec_modal_admin_tg: 'Telegram Admin',
    sec_modal_admin_open_tg: 'បើកក្នុង Telegram',
    sec_modal_admin_close: 'បិទ',
    sec_modal_admin_copy: 'ចម្លង',
    sec_modal_admin_copied: 'បានចម្លង'
  },
  en: {
    app_title: 'Wat Snay Duoc Data Management',
    nav_home: 'Home',
    nav_finance: 'Finances',
    nav_list: 'Other Lists',
    nav_reports: 'Reports',
    nav_account: 'Account',
    
    common_back: 'Back',
    common_loading: 'Loading...',
    common_saving: 'Saving...',
    common_no_data: 'No data available yet',
    common_show: 'Show',
    common_hide: 'Hide',
    common_search: 'Search...',

    profile_account_menu: 'Account',
    profile_security_menu: 'Password & Security',
    profile_setting_menu: 'Settings',
    profile_syslog_menu: 'System Logs',
    profile_setting_modal_title: 'Settings',
    profile_setting_lang_heading: 'Language:',
    profile_setting_lang_km: 'Khmer',
    profile_setting_lang_km_desc: 'All text in this app will be changed to Khmer Language.',
    profile_setting_lang_en: 'English',
    profile_setting_lang_en_desc: 'All text in this app will be changed to English Language.',
    profile_setting_theme_heading: 'Theme:',
    profile_setting_theme_dark: 'Dark mode',
    profile_setting_theme_light: 'Light mode',
    profile_setting_fontsize_heading: 'Font Size:',
    profile_setting_fontsize_sm: 'Small',
    profile_setting_fontsize_sm_desc: '90% - Suitable for small screens or viewing more content',
    profile_setting_fontsize_md: 'Default',
    profile_setting_fontsize_md_desc: '100% - Standard application font size',
    profile_setting_fontsize_lg: 'Large',
    profile_setting_fontsize_lg_desc: '110% - Comfortable and clear readability',
    profile_setting_fontsize_xl: 'Extra Large',
    profile_setting_fontsize_xl_desc: '120% - Maximum readability, ideal for elderly users',
    profile_setting_fontsize_preview: 'Preview: Wat Snay Duoc Financial & Donor Records $1,000',
    profile_setting_role_heading: 'Role:',
    profile_setting_role_admin: 'Admin',
    profile_setting_role_user: 'User',
    profile_setting_btn_use: 'Use',
    profile_setting_btn_used: 'Used',
    profile_setting_storage_heading: 'Storage:',
    profile_setting_storage_label: 'Temporary Cache & Logs',
    profile_setting_storage_desc: 'Clear system logs and temporary cache to free up memory.',
    profile_setting_storage_clean_btn: 'Clear',
    profile_setting_storage_confirm: 'Confirm clear?',
    profile_setting_storage_cleaned: 'Cleared',
    profile_role_menu: 'Change User Role',
    profile_role_modal_title: 'Change User Role',
    profile_role_admin_title: 'Administrator (Admin)',
    profile_role_admin_desc: 'Full access to manage, edit, create, and delete all records and settings.',
    profile_role_user_title: 'General Member (User)',
    profile_role_user_desc: 'Standard viewing and restricted data submission privileges.',
    profile_role_current: 'Active Role',
    profile_security_modal_title: 'Password & Security',
    profile_change_password_title: 'Password',
    profile_change_password_desc: 'Change account password',
    profile_pin_balance_title: 'Balance View PIN',
    profile_pin_balance_set: 'Already configured',
    profile_pin_balance_unset: 'Not configured yet',
    profile_settings_heading: 'Settings:',
    profile_change_lang: 'Change Language',
    profile_change_theme: 'Change Theme',
    profile_theme_modal_title: 'Change Theme',
    profile_theme_light_label: 'Light Mode',
    profile_theme_dark_label: 'Dark Mode',
    profile_mgmt_heading: 'Management:',
    profile_certificates: 'Certificates & Documents',
    profile_users: 'User Management',
    profile_introduced: 'Installation Guide',
    profile_about: 'About App',
    profile_logout: 'Logout',

    theme_dark: 'Dark',
    theme_light: 'Light',
    
    about_tab_info: 'About App',
    about_tab_introduced: 'Installation Guide',
    about_purpose: 'Purpose',
    about_purpose_desc: 'This application is built to manage the database of income, expenses, and various donor lists for Wat Snay Duoc.',
    about_dev: 'Developed By',
    about_tech: 'Technologies',
    about_close: 'Close',
    about_version: 'Version',
    install_already_installed: 'App is already installed on this device',
    install_android_desc: 'You can install Wat Snay Duoc app on your Android device for quick, smooth, and convenient access.',
    install_btn_installing: 'Preparing...',
    install_btn_install: 'Install App',
    install_android_steps_title: 'Steps to install via Chrome or Samsung Internet:',
    install_android_step_1_prefix: 'Open app via ',
    install_android_step_1_or: ' or ',
    install_android_step_2: 'Tap the options menu icon (⋮) at top-right corner',
    install_android_step_3: 'Select "Install app" or "Add to Home screen"',
    install_android_step_4: 'Tap "Install" to complete installation',
    install_ios_desc: 'For iPhone / iPad, please open in Safari and follow the steps below:',
    install_ios_steps_title: 'Steps to add to Home Screen:',
    install_ios_step_1: 'Open the link in Safari',
    install_ios_step_2: 'Tap the Share button on the bottom bar',
    install_ios_step_3: 'Scroll down and select "Add to Home Screen"',
    install_ios_step_4: 'Tap "Add" at the top-right corner to finish',
    install_ios_copy_btn: 'Copy link to open in Safari',
    install_ios_copied: 'Link copied successfully!',
    
    lang_khmer: 'ភាសាខ្មែរ',
    lang_english: 'English',

    dashboard_title: 'Data Analysis',
    dashboard_total_report: 'Total Report (Period: {count} Seil)',
    dashboard_total_income: 'Total Income',
    dashboard_total_expense: 'Total Expense',
    dashboard_actual_balance: 'Actual Remaining Balance',
    dashboard_chart_title: 'Income and Expense by Seil',
    dashboard_income: 'Income',
    dashboard_expense: 'Expense',
    dashboard_pie_title: 'Financial Proportion',
    dashboard_amount: 'Amount',
    dashboard_high_donors: 'High-Tier Donors',
    dashboard_donors_count: '{count} Donors',

    records_title: 'Finances',
    records_total_periods: 'Total {count} Periods',
    records_btn_add_new: 'Add New',
    records_add_new: 'Add New Record',
    records_prev_balance: 'Previous Balance',
    records_current_balance: 'Actual Balance',
    records_total_income: 'Total Income',
    records_total_expense: 'Total Expense',
    records_empty_income: 'No income records yet',
    records_empty_expense: 'No expense records yet',
    records_add_new_title: 'Add New Data',
    records_type_income: 'Income',
    records_type_expense: 'Expense',
    records_description_income: 'Donor Name',
    records_description_income_ph: 'Enter name',
    records_description_expense: 'Description (Item)',
    records_description_expense_ph: 'Ex: Bought Water...',
    records_amount: 'Amount (Riel)',
    records_amount_ph: '00,000',
    records_date: 'Date',
    records_note: 'Note (Optional)',
    records_note_ph: 'Optional',
    records_save: 'Save Data',

    lists_main_title: 'Other Lists',
    lists_category_roof: 'Temple Roof Construction',
    lists_category_kathina: 'Kathina Ceremony',
    lists_category_general: 'General Lists',
    lists_status_active: 'In Progress',
    lists_status_completed: 'Completed',
    lists_no_lists: 'No lists available yet',
    list_title: 'Name List',
    list_add_new: 'Add Data',
    list_search: 'Search names or places...',
    list_date: 'Date',
    list_total_records: 'Total Records',
    list_total_amount: 'Total',
    list_empty: 'No records found',
    list_referrer: 'Referred by',
    list_edit_title: 'Edit Data',
    list_add_title: 'Add New Data',
    list_name: 'Name',
    list_name_ph: 'Enter name...',
    list_amount: 'Amount (Riel)',
    list_amount_ph: 'Ex: 100000',
    list_note: 'Section',
    list_note_ph: 'Ex: Phnom Penh...',
    list_ref: 'Referrer (Optional)',
    list_ref_ph: 'Enter referrer name...',
    list_cancel: 'Cancel',
    list_save: 'Save',
    list_alert_delete: 'Are you sure you want to delete this record?',
    list_alert_error: 'Error saving data',
    list_alert_del_error: 'Error deleting data',

    reports_saved_title: 'Saved Reports',
    reports_empty: 'No saved reports yet',
    reports_preview_title: 'Report Preview',
    reports_download: 'Download',
    reports_delete: 'Delete',
    reports_delete_confirm_title: 'Confirm Deletion',
    reports_delete_confirm_msg: 'Are you sure you want to delete this report? This action cannot be undone.',
    reports_cancel: 'Cancel',
    reports_preview_hint: 'Click to preview image',

    cert_title: 'Certificates of Appreciation',
    cert_total: 'Total {count}',
    cert_search_ph: 'Search name...',
    cert_not_found: 'No matching certificates found',
    cert_empty: 'No certificates available yet',
    cert_btn_view: 'View',
    cert_btn_download: 'Download',
    cert_btn_delete: 'Delete',
    cert_modal_view_title: 'View Certificate',
    cert_delete_confirm_title: 'Delete Certificate?',
    cert_delete_confirm_desc: 'Are you sure you want to delete this certificate? This action cannot be undone.',

    users_title: 'User Management',
    users_subtitle: 'Manage roles and accounts',
    users_tab_list: 'User List',
    users_tab_advanced: 'Advanced Controls',
    users_col_id: 'ID',
    users_col_name: 'Name',
    users_col_email: 'Email',
    users_col_role: 'Roles',
    users_col_status: 'Status',
    users_col_actions: 'Actions',
    users_search_ph: 'Search name, email, or phone...',
    users_no_name: 'No Name',
    users_registered_at: 'Registered:',
    users_role_admin: 'Admin',
    users_role_user: 'User',
    users_btn_reset_pwd: 'Reset Password',
    users_reset_pwd_title: 'Reset User Password',
    users_new_pwd_ph: 'Enter new password (min 6 chars)',
    users_btn_save_pwd: 'Update Password',
    users_confirm_role_change: 'Are you sure you want to change this user role to {role}?',

    profile_title: 'Profile',
    profile_view_edit: 'View and edit profile',
    profile_settings: 'Management',
    profile_finance_mgmt: 'Finances',
    profile_list_mgmt: 'Name Lists',
    profile_security_title: 'Your account is secure',
    profile_security_desc: 'Your data is well protected',
    profile_others: 'Settings',
    profile_edit_title: 'Edit Profile',
    profile_edit_photo: 'Click camera to change photo',
    profile_full_name: 'Full Name',
    profile_password: 'Password',
    profile_password_ph: 'Leave blank to keep current password',
    profile_save_changes: 'Save Changes',
    profile_saving: 'Saving...',
    profile_role_admin: 'Administrator',
    profile_role_user: 'User',
    profile_personal_details: 'Personal Details',
    profile_khmer_name: 'Khmer Name',
    profile_khmer_name_ph: 'Enter Khmer name',
    profile_latin_name: 'Latin Name',
    profile_latin_name_ph: 'Enter Latin / English name',
    profile_unverified: 'Unverified',
    profile_unverified_desc: 'Please complete your personal details (Date of Birth, Address, Phone) to verify your account.',
    profile_family_name: 'Family Name',
    profile_family_name_ph: 'Family Name',
    profile_given_name: 'Given Name',
    profile_given_name_ph: 'Given Name',
    profile_dob: 'Date of Birth',
    profile_dob_ph: 'DD/MM/YYYY',
    profile_gender: 'Gender',
    profile_gender_male: 'Male',
    profile_gender_female: 'Female',
    profile_address: 'Address',
    profile_address_ph: 'Address',
    profile_email: 'Email',
    profile_email_ph: 'Email',
    profile_phone: 'Phone Number',
    profile_phone_ph: 'Phone Number',
    profile_btn_edit: 'Edit',
    profile_btn_save: 'Save Profile',
    profile_save_success: 'Profile saved successfully!',
    profile_save_error: 'Failed to save profile. Please try again.',
    profile_avatar_success: 'Profile photo updated successfully!',
    profile_avatar_error: 'Failed to upload photo. Please try again.',
    dashboard_verify_pin_title: 'Verify PIN',
    dashboard_verify_pin_sub: 'Please enter your 4-digit PIN to view balance',

    install_title: 'Install App',
    install_desc: 'Install this app on your home screen for quick and easy access.',
    install_btn: 'Install',

    sec_title: 'Password & Security',
    sec_pwd_label: 'Password',
    sec_pwd_desc: 'We recommend using a secure password that you don\'t use anywhere else.',
    sec_pin_label: 'PIN',
    sec_pin_desc: 'Change your PIN used on this app.',
    sec_email_label: 'Email',
    sec_phone_label: 'Phone Number',
    sec_contact_label: 'Contact:',
    sec_change_btn: 'change',
    sec_change_cap_btn: 'Change',
    
    sec_modal_pwd_title: 'Change Password',
    sec_modal_pwd_new: 'New Password',
    sec_modal_pwd_new_ph: 'Enter new password (min. 6 characters)',
    sec_modal_pwd_confirm: 'Confirm New Password',
    sec_modal_pwd_confirm_ph: 'Re-enter new password',
    sec_modal_pwd_save: 'Save Changes',
    sec_modal_pwd_err_len: 'Password must be at least 6 characters',
    sec_modal_pwd_err_match: 'Passwords do not match',
    sec_modal_pwd_err_fail: 'Failed to change password',
    sec_modal_pwd_success: 'Password changed successfully',

    sec_modal_pin_verify_title: 'Verify Current PIN',
    sec_modal_pin_verify_sub: 'Please enter your current PIN',
    sec_modal_pin_new_title: 'Set New PIN',
    sec_modal_pin_new_sub: 'Please enter a new 4-digit PIN',
    sec_modal_pin_confirm_title: 'Confirm New PIN',
    sec_modal_pin_confirm_sub: 'Please re-enter the new PIN to confirm',
    sec_modal_pin_err_match: 'PINs do not match',
    sec_modal_pin_err_incorrect: 'Current PIN is incorrect',
    sec_modal_pin_err_fail: 'Failed to set PIN',
    sec_modal_pin_success: 'PIN updated successfully',

    sec_modal_email_title: 'Change Email',
    sec_modal_email_label: 'New Email',
    sec_modal_email_ph: 'name@example.com',
    sec_modal_email_save: 'Save Changes',
    sec_modal_email_err_invalid: 'Please enter a valid email address',
    sec_modal_email_err_fail: 'Failed to change email',
    sec_modal_email_success: 'Email changed successfully',

    sec_modal_phone_title: 'Change Phone Number',
    sec_modal_phone_label: 'New Phone Number',
    sec_modal_phone_ph: '012 345 678',
    sec_modal_phone_save: 'Save Changes',
    sec_modal_phone_err_req: 'Please enter a phone number',
    sec_modal_phone_err_fail: 'Failed to change phone number',
    sec_modal_phone_success: 'Phone number changed successfully',

    sec_modal_admin_title: 'Contact Admin',
    sec_modal_admin_tg: 'Telegram Admin',
    sec_modal_admin_open_tg: 'Open in Telegram',
    sec_modal_admin_close: 'Close',
    sec_modal_admin_copy: 'Copy',
    sec_modal_admin_copied: 'Copied'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('km');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'km' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    if (language === 'en') {
      document.documentElement.classList.add('lang-en');
      document.documentElement.classList.remove('lang-km');
    } else {
      document.documentElement.classList.add('lang-km');
      document.documentElement.classList.remove('lang-en');
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const keys = key.split('.');
    let result: any = translations[language];
    
    for (const k of keys) {
      if (result && result[k] !== undefined) {
        result = result[k];
      } else {
        return key; // return key if translation not found
      }
    }
    
    if (typeof result === 'string' && params) {
      return result.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? String(params[k]) : `{${k}}`);
    }
    
    return result as string;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
