
DO $$
DECLARE
    cat_id UUID;
BEGIN
    -- Get the ID of the new category
    SELECT id INTO cat_id FROM public.name_list_categories WHERE name = 'បញ្ជីឈ្មោះបុណ្យផ្កា' LIMIT 1;
    
    -- Delete existing records for this category
    DELETE FROM public.name_list_records WHERE category_id = cat_id;

    -- Insert the visible records from the image
    INSERT INTO public.name_list_records (category_id, name, amount, note, referrer) VALUES
    (cat_id, 'ឧបាសិកា ហៃ ព្រមទាំងកូនចៅ', 100000, NULL, NULL),
    (cat_id, 'កុង សៅ យាយ ផេង ព្រមទាំងកូនចៅ', 40000, 'ជើងកូន', NULL),
    (cat_id, 'វត្ត ក្ដីទឹម', 150000, NULL, NULL),
    (cat_id, 'វត្ត អង្គមានជ័យ', 235000, NULL, NULL),
    (cat_id, 'វត្ត អង្គជ្រៃ', 120000, NULL, NULL),
    (cat_id, 'វត្ត ត្រាសោមង្គល', 140000, NULL, NULL),
    (cat_id, 'ភូមិស្វាយចេក', 100000, NULL, NULL),
    (cat_id, 'ត្រាលើ', 158000, NULL, NULL),
    (cat_id, 'ត្បួច', 225000, NULL, NULL),
    (cat_id, 'តាខុយ', 120000, NULL, NULL),
    (cat_id, 'ភូមិថ្មី', 260000, NULL, NULL),
    (cat_id, 'ស្វាយពារ', 370000, NULL, NULL),
    (cat_id, 'ក្បាលសំរោង', 150000, NULL, NULL),
    (cat_id, 'រដ្ឋបាលឃុំជើងកូន', 80000, NULL, NULL),
    (cat_id, 'ភូមិសន្លុងមន្ត្រី', 350000, NULL, NULL),
    (cat_id, 'ភូមិក្រាំងឡូង', 100000, NULL, NULL),
    (cat_id, 'អង្គខាងលិច', 70000, NULL, NULL),
    (cat_id, 'ត្រពាំងវិហារ', 200000, NULL, NULL),
    (cat_id, 'ភូមិព្រៃបេង', 3040000, 'មានបញ្ជីឈ្មោះ', NULL),
    (cat_id, 'វត្ត ខ្សាច់ស', 140000, NULL, NULL),
    (cat_id, 'ទ្រី-ដា', 20000, 'ជើងកូន', NULL),
    (cat_id, 'មាន ស្រ៊ាង ព្រមទាំងកូនចៅ', 200000, NULL, NULL),
    (cat_id, 'សល់-តា', 20000, 'ជើងកូន', NULL),
    (cat_id, 'គន ចាន់ណា', 10000, NULL, NULL),
    (cat_id, 'បញ្ញា លីម', 20000, NULL, NULL),
    (cat_id, 'កុងផាន់ យ៉ែត ព្រមទាំងកូនចៅ', 30000, NULL, NULL),
    (cat_id, 'ជឿន-វី', 60000, 'ជើងកូន', NULL),
    (cat_id, 'ភា-ភាព', 15000, NULL, NULL),
    (cat_id, 'យីម វុឌ្ឍី', 30000, NULL, NULL),
    (cat_id, 'ឈុន សុខា', 10000, NULL, NULL),
    (cat_id, 'ដាវ យ៉េន', 50000, NULL, NULL),
    (cat_id, 'យាយ ស្រី', 10000, NULL, NULL),
    (cat_id, 'យាយ ណែម', 10000, NULL, NULL),
    (cat_id, 'លោកយាយ ផេង ព្រមទាំងកូនចៅ', 10000, NULL, NULL),
    (cat_id, 'ហេង លាង ព្រមទាំងកូនចៅ', 10000, NULL, NULL),
    (cat_id, 'លោកយាយ ផេង ព្រមទាំងកូនចៅ', 15000, NULL, NULL),
    (cat_id, 'យាយ ស្រី', 20000, NULL, NULL),
    (cat_id, 'យាយ ណែម', 10000, NULL, NULL),
    (cat_id, 'គ្រូ សុខ សុខន', 5000, NULL, NULL),
    (cat_id, 'គន ចេង', 10000, NULL, NULL),
    (cat_id, 'សុខា ហ៊ាន', 20000, NULL, NULL),
    (cat_id, 'ស៊ី ផែន', 5000, NULL, NULL),
    (cat_id, 'ប៉ូល អ៊ឹម', 10000, NULL, NULL),
    (cat_id, 'ជូ យ៉ាន', 10000, NULL, NULL),
    (cat_id, 'ចឹង លន់', 10000, NULL, NULL),
    (cat_id, 'ធី រ៉ែម', 10000, NULL, NULL),
    (cat_id, 'ខេម ឡាយ', 100000, NULL, NULL),
    (cat_id, 'តឿន ហេង', 20000, NULL, NULL),
    (cat_id, 'ខេន សម្បត្តិ', 50000, NULL, NULL),
    (cat_id, 'លោកគ្រូ សុខ អ្នកគ្រូ កល្យាណ', 20000, NULL, NULL),
    (cat_id, 'ពេទ្យ បុល ផល្លា', 20000, NULL, NULL),
    (cat_id, 'គ្រូ ទៀង ភារិយា', 10000, NULL, NULL),
    (cat_id, 'កាំង យាន ព្រមទាំងកូនចៅ', 20000, NULL, NULL),
    (cat_id, 'ស្ទៀង វណ្ណី ព្រមទាំងកូនចៅ', 100000, NULL, NULL),
    (cat_id, 'វត្ត បាណន្តគ្រោះ', 20000, NULL, NULL),
    (cat_id, 'វត្ត អំពិលបី ព្រមទាំងកូនចៅ', 200000, NULL, NULL),
    (cat_id, 'វត្ត បាណន្តគ្រោះ', 20000, NULL, NULL),
    (cat_id, 'វត្ត អំពិលបី', 20000, NULL, NULL),
    (cat_id, 'ស្ទៀង វណ្ណី', 10000, NULL, NULL),
    (cat_id, 'កាំង យាន ព្រមទាំងកូនចៅ', 100000, NULL, NULL),
    (cat_id, 'គ្រូ ទៀង ភារិយា', 20000, NULL, NULL),
    (cat_id, 'ពេទ្យ បុល ផល្លា', 15000, NULL, NULL),
    (cat_id, 'លោកគ្រូ សុខ អ្នកគ្រូ កល្យាណ', 40000, NULL, NULL),
    (cat_id, 'ខេន សម្បត្តិ', 10000, NULL, NULL),
    (cat_id, 'តឿន ហេង', 20000, NULL, NULL),
    (cat_id, 'ខេម ឡាយ', 10000, 'ជើងកូន', NULL),
    (cat_id, 'ធី រ៉ែម', 20000, 'ជើងកូន', NULL),
    (cat_id, 'ចឹង លន់', 10000, NULL, NULL),
    (cat_id, 'ជូ យ៉ាន', 20000, NULL, NULL),
    (cat_id, 'ប៉ូល អ៊ឹម', 20000, NULL, NULL),
    (cat_id, 'ស៊ី ផែន', 10000, NULL, NULL),
    (cat_id, 'សុខា ហ៊ាន', 20000, NULL, NULL),
    (cat_id, 'គន ចេង ព្រមទាំងកូនចៅ', 40000, NULL, NULL),
    (cat_id, 'គ្រូ សុខ សុខន', 15000, NULL, NULL),
    (cat_id, 'យាយ ណែម', 10000, NULL, NULL),
    (cat_id, 'យាយ ស្រី', 30000, NULL, NULL),
    (cat_id, 'លោកយាយ ផេង ព្រមទាំងកូនចៅ', 20000, NULL, NULL),
    (cat_id, 'ហេង លាង ព្រមទាំងកូនចៅ', 10000, NULL, NULL),
    (cat_id, 'លោកយាយ ផេង ព្រមទាំងកូនចៅ', 20000, NULL, NULL),
    (cat_id, 'ដាវ យ៉េន', 10000, 'ជើងកូន', NULL),
    (cat_id, 'ឈុន សុខា', 20000, NULL, NULL),
    (cat_id, 'យីម វុឌ្ឍី', 30000, NULL, NULL),
    (cat_id, 'ភា-ភាព', 10000, NULL, NULL),
    (cat_id, 'ជឿន-វី', 100000, NULL, NULL),
    (cat_id, 'កុងផាន់ យ៉ែត ព្រមទាំងកូនចៅ', 15000, NULL, NULL),
    (cat_id, 'បញ្ញា លីម', 10000, NULL, NULL),
    (cat_id, 'គន ចាន់ណា', 5000, NULL, NULL),
    (cat_id, 'សល់-តា', 20000, NULL, NULL),
    (cat_id, 'មាន ស្រ៊ាង ព្រមទាំងកូនចៅ', 662000, NULL, NULL),
    (cat_id, 'ទ្រី-ដា ព្រមទាំងកូនចៅ', 15000, NULL, NULL),
    (cat_id, 'វត្ត ខ្សាច់ស', 100000, NULL, NULL),
    (cat_id, 'ភូមិព្រៃបេង', 20000, NULL, NULL),
    (cat_id, 'ត្រពាំងវិហារ', 15000, NULL, NULL),
    (cat_id, 'អង្គខាងលិច', 20000, NULL, NULL),
    (cat_id, 'ភូមិក្រាំងឡូង', 5000, NULL, NULL),
    (cat_id, 'ភូមិសន្លុងមន្ត្រី', 10000, NULL, NULL),
    (cat_id, 'រដ្ឋបាលឃុំជើងកូន (ជើងកូន)', 180000, 'ជើងកូន', NULL),
    (cat_id, 'ក្បាលសំរោង', 20000, NULL, NULL),
    (cat_id, 'ស្វាយពារ', 100000, 'ជើងកូន', NULL),
    (cat_id, 'ភូមិថ្មី', 40000, NULL, NULL),
    (cat_id, 'តាខុយ', 20000, NULL, NULL),
    (cat_id, 'ត្បួច ព្រមទាំងកូនចៅ', 300000, NULL, NULL),
    (cat_id, 'ត្រាលើ', 100000, NULL, NULL),
    (cat_id, 'ភូមិស្វាយចេក', 50000, NULL, NULL),
    (cat_id, 'វត្ត ត្រាសោមង្គល', 300000, 'ជើងកូន', NULL),
    (cat_id, 'វត្ត អង្គជ្រៃ ព្រមទាំងកូនចៅ', 120000, NULL, NULL),
    (cat_id, 'វត្ត អង្គមានជ័យ', 20000, NULL, NULL),
    (cat_id, 'វត្ត ក្ដីទឹម', 20000, NULL, NULL),
    (cat_id, 'កុង សៅ យាយ ផេង', 40000, 'ជើងកូន', NULL),
    (cat_id, 'ឧបាសិកា ហៃ ព្រមទាំងកូនចៅ', 15000, NULL, NULL),
    (cat_id, 'វត្ត ក្ដីទឹម', 10000, NULL, NULL),
    (cat_id, 'វត្ត អង្គមានជ័យ', 200000, NULL, NULL),
    (cat_id, 'វត្ត អង្គជ្រៃ', 120000, NULL, NULL);
END $$;
